In [ ]:
nan-not a number
None-
methods after checking nan value present or not:-
        fillna, replace, interpolate, dropna

In [1]:
#fillna
import pandas as pd
import numpy as np

In [4]:
d={"Apple":[45,25,np.nan, 15, np.nan,54],"Orange":[12,13,56,78,95,np.nan],"Grapes":[1,2,3,4,8,9],"papaya":[45,np.nan,74,56,23,15]}

In [5]:
d

{'Apple': [45, 25, nan, 15, nan, 54],
 'Orange': [12, 13, 56, 78, 95, nan],
 'Grapes': [1, 2, 3, 4, 8, 9],
 'papaya': [45, nan, 74, 56, 23, 15]}

In [6]:
df=pd.DataFrame(d)
df

   Apple  Orange  Grapes  papaya
0   45.0    12.0       1    45.0
1   25.0    13.0       2     NaN
2    NaN    56.0       3    74.0
3   15.0    78.0       4    56.0
4    NaN    95.0       8    23.0
5   54.0     NaN       9    15.0

In [7]:
#to check null values
df.isnull()

   Apple  Orange  Grapes  papaya
0  False   False   False   False
1  False   False   False    True
2   True   False   False   False
3  False   False   False   False
4   True   False   False   False
5  False    True   False   False

In [8]:
#which column have nan and no. of nan values in column
df.isnull().sum()

Apple     2
Orange    1
Grapes    0
papaya    1
dtype: int64

In [9]:
df.notnull()

   Apple  Orange  Grapes  papaya
0   True    True    True    True
1   True    True    True   False
2  False    True    True    True
3   True    True    True    True
4  False    True    True    True
5   True   False    True    True

In [10]:
df.notnull().sum()

Apple     4
Orange    5
Grapes    6
papaya    5
dtype: int64

In [11]:
df.fillna(0)

   Apple  Orange  Grapes  papaya
0   45.0    12.0       1    45.0
1   25.0    13.0       2     0.0
2    0.0    56.0       3    74.0
3   15.0    78.0       4    56.0
4    0.0    95.0       8    23.0
5   54.0     0.0       9    15.0

In [12]:
df.fillna(1) #but this method is not efficient it can effect accuracy

   Apple  Orange  Grapes  papaya
0   45.0    12.0       1    45.0
1   25.0    13.0       2     1.0
2    1.0    56.0       3    74.0
3   15.0    78.0       4    56.0
4    1.0    95.0       8    23.0
5   54.0     1.0       9    15.0

In [13]:
df.fillna(method="pad") #it will show warning

C:\Users\sai\AppData\Local\Temp\ipykernel_8820\4167762737.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="pad")

   Apple  Orange  Grapes  papaya
0   45.0    12.0       1    45.0
1   25.0    13.0       2    45.0
2   25.0    56.0       3    74.0
3   15.0    78.0       4    56.0
4   15.0    95.0       8    23.0
5   54.0    95.0       9    15.0

In [14]:
df.fillna(method="ffill")

C:\Users\sai\AppData\Local\Temp\ipykernel_8820\169247090.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")

   Apple  Orange  Grapes  papaya
0   45.0    12.0       1    45.0
1   25.0    13.0       2    45.0
2   25.0    56.0       3    74.0
3   15.0    78.0       4    56.0
4   15.0    95.0       8    23.0
5   54.0    95.0       9    15.0

In [15]:
df.ffill() #if first column has nan it remains nan

   Apple  Orange  Grapes  papaya
0   45.0    12.0       1    45.0
1   25.0    13.0       2    45.0
2   25.0    56.0       3    74.0
3   15.0    78.0       4    56.0
4   15.0    95.0       8    23.0
5   54.0    95.0       9    15.0

In [18]:
df.bfill()

   Apple  Orange  Grapes  papaya
0   45.0    12.0       1    45.0
1   25.0    13.0       2    74.0
2   15.0    56.0       3    74.0
3   15.0    78.0       4    56.0
4   54.0    95.0       8    23.0
5   54.0     NaN       9    15.0

In [16]:
d={"Apple":[45,25,np.nan, 15, np.nan,54],"Orange":[12,13,56,78,95,np.nan],"Grapes":[np.nan,2,3,4,8,9],"papaya":[45,np.nan,74,56,23,15]}

In [17]:
d

{'Apple': [45, 25, nan, 15, nan, 54],
 'Orange': [12, 13, 56, 78, 95, nan],
 'Grapes': [nan, 2, 3, 4, 8, 9],
 'papaya': [45, nan, 74, 56, 23, 15]}

In [19]:
#limitation
df=pd.DataFrame(d)
df.ffill()

   Apple  Orange  Grapes  papaya
0   45.0    12.0     NaN    45.0
1   25.0    13.0     2.0    45.0
2   25.0    56.0     3.0    74.0
3   15.0    78.0     4.0    56.0
4   15.0    95.0     8.0    23.0
5   54.0    95.0     9.0    15.0

In [20]:
df.replace(np.nan,23)

   Apple  Orange  Grapes  papaya
0   45.0    12.0    23.0    45.0
1   25.0    13.0     2.0    23.0
2   23.0    56.0     3.0    74.0
3   15.0    78.0     4.0    56.0
4   23.0    95.0     8.0    23.0
5   54.0    23.0     9.0    15.0

In [24]:
df.interpolate() #eg at [2,"apple"]=nan calculated as ([1,"apple"]+[3,"apple"])/2

   Apple  Orange  Grapes  papaya
0   45.0    12.0     NaN    45.0
1   25.0    13.0     2.0    59.5
2   20.0    56.0     3.0    74.0
3   15.0    78.0     4.0    56.0
4   34.5    95.0     8.0    23.0
5   54.0    95.0     9.0    15.0

In [25]:
df.dropna() #drops those columns which has nan

   Apple  Orange  Grapes  papaya
3   15.0    78.0     4.0    56.0

In [26]:
df=df.dropna() #updates df

In [27]:
df

   Apple  Orange  Grapes  papaya
3   15.0    78.0     4.0    56.0

In [32]:
d={"Apple":[45,25,np.nan, 15, np.nan,54],"Orange":[12,13,56,78,95,np.nan],"Grapes":[np.nan,2,3,4,8,9],"papaya":[45,np.nan,74,56,23,15]}
df=pd.DataFrame(d)

In [33]:
df.dropna(axis=1) # when 1 it checks column wise if any nan exists in that column it will drop if 0 given it will check rowwise

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5]

In [34]:
df.dropna(axis=0)

   Apple  Orange  Grapes  papaya
3   15.0    78.0     4.0    56.0