In [ ]:
#how to deal with categorical values

In [1]:
"""  types of data- nominal-order does not matter . OneHotEncoder
                    ordinal- order matters . OrdinalEncoder , labelencoder(for target) ,TargetGuidedEncoder
    Goal is to use encoder to convert text to numeric form
    
                    """

'  types of data- nominal-order does not matter . OneHotEncoder\n                    ordinal- order matters . OrdinalEncoder , labelencoder(for target) ,TargetGuidedEncoder\n    Goal is to use encoder to convert text to numeric form\n    \n                    '

In [2]:
#OneHotEncoder
#easy to implement but it lead to overfitting and make sparse matrix
#no. of rows=no of columns  will be added to previous data
d={"Apple"=["delicious","sarampuri","redapple","gala","golden"],"size":[40,50,60,20,25]}
 
apple           size    delicious    sarampuri    redapple   gala   golden
delicious        40       1             0             0        0      0
sarampuri        50       0             1             0        0      0
redapple         60       0             0             1        0      0   
gala             20       0             0             0        1      0 
golden           25       0             0             0        0      1

SyntaxError: cannot assign to literal here. Maybe you meant '==' instead of '='? (3656477514.py, line 4)

In [3]:
#onehotencoder
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [4]:
d={"fruits":["Apple","Banana","Orange","Apple","Banana","Orange"],"color":["Red","yellow","orange","Red","yellow","orange"],
  "size":[12,23,14,12,23,14]}
d

{'fruits': ['Apple', 'Banana', 'Orange', 'Apple', 'Banana', 'Orange'],
 'color': ['Red', 'yellow', 'orange', 'Red', 'yellow', 'orange'],
 'size': [12, 23, 14, 12, 23, 14]}

In [5]:
df=pd.DataFrame(d)
df

   fruits   color  size
0   Apple     Red    12
1  Banana  yellow    23
2  Orange  orange    14
3   Apple     Red    12
4  Banana  yellow    23
5  Orange  orange    14

In [8]:
encoder=OneHotEncoder()

In [7]:
#fit -use formula but not use calculated value by formula
#fit_transform -use formula and use calculated value
encoder.fit_transform(df[["fruits"x=]]) #3 unique rows and add these as column so (6,3)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2206026476.py, line 3)

In [9]:
encoder.fit_transform(df[["fruits"]]).toarray()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
en=encoder.fit_transform(df[["fruits"]])

In [11]:
en

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6 stored elements and shape (6, 3)>

In [12]:
x=pd.DataFrame(en.toarray(), columns=encoder.get_feature_names_out())

In [13]:
x

   fruits_Apple  fruits_Banana  fruits_Orange
0           1.0            0.0            0.0
1           0.0            1.0            0.0
2           0.0            0.0            1.0
3           1.0            0.0            0.0
4           0.0            1.0            0.0
5           0.0            0.0            1.0

In [14]:
pd.concat([df,x],axis=1)

   fruits   color  size  fruits_Apple  fruits_Banana  fruits_Orange
0   Apple     Red    12           1.0            0.0            0.0
1  Banana  yellow    23           0.0            1.0            0.0
2  Orange  orange    14           0.0            0.0            1.0
3   Apple     Red    12           1.0            0.0            0.0
4  Banana  yellow    23           0.0            1.0            0.0
5  Orange  orange    14           0.0            0.0            1.0

In [15]:
en=encoder.fit_transform(df[["fruits","color"]]).toarray()

In [16]:
x=pd.DataFrame(en, columns=encoder.get_feature_names_out())

In [17]:
x

,fruits_Apple,fruits_Banana,fruits_Orange,color_Red,color_orange,color_yellow
0,1.0,0.0,0.0,1.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,1.0
2,0.0,0.0,1.0,0.0,1.0,0.0
3,1.0,0.0,0.0,1.0,0.0,0.0
4,0.0,1.0,0.0,0.0,0.0,1.0
5,0.0,0.0,1.0,0.0,1.0,0.0

In [18]:
pd.concat([df,x],axis=1)

,fruits,color,size,fruits_Apple,fruits_Banana,fruits_Orange,color_Red,color_orange,color_yellow
0,Apple,Red,12,1.0,0.0,0.0,1.0,0.0,0.0
1,Banana,yellow,23,0.0,1.0,0.0,0.0,0.0,1.0
2,Orange,orange,14,0.0,0.0,1.0,0.0,1.0,0.0
3,Apple,Red,12,1.0,0.0,0.0,1.0,0.0,0.0
4,Banana,yellow,23,0.0,1.0,0.0,0.0,0.0,1.0
5,Orange,orange,14,0.0,0.0,1.0,0.0,1.0,0.0

In [19]:
#ordinal encoder, Label encoder 
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder

d1={"Education":["Phd","Pg","Ug","School"],
    "Review":["Excellent","Very good","Good","poor"],
    "Result":["yes","No","Yes","No"]}
df1=pd.DataFrame(d1)
df1

  Education     Review Result
0       Phd  Excellent    yes
1        Pg  Very good     No
2        Ug       Good    Yes
3    School       poor     No